name: Release to production

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release-please:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'release-please--branches--main--components--yargs'
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
    steps:
      - name: Release Please
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

